---
root: true

extends:
  - airbnb
  - prettier
  - prettier/react

plugins:
  - prettier

env:
  es6: true
  browser: true
  node: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules:
  import/prefer-default-export: off
  comma-dangle: off
  prefer-const: off
